CrazyEye/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from web import views,api_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^kingadmin/', include('kingadmin.urls')),
     #url(r'^myadmin/', include(cus_admin.admin_site.urls)),
    url(r'session_security/', include('session_security.urls')),
    url(r'^$',views.dashboard ,name='dashboard'),
    url(r'^hosts/$',views.hosts, name='host_list' ),
    url(r'^hosts/multi/$',views.hosts_multi,name="batch_cmd_exec"),
    url(r'^hosts/crontab/$',views.crontab),
    url(r'^multi_task/log/deatail/(\d+)/$',views.multi_task_log_detail,name='multi_task_log_detail'),
    url(r'^hosts/multi/filetrans$',views.hosts_multi_filetrans,name="batch_file_transfer"),
    url(r'^host/detail/', views.host_detail),
    url(r'^api/',include(api_urls)),
    url(r'^personal/',views.personal,name='personal'),
    url(r'^user_audit/(\d+)/$',views.user_audit, name='user_audit'),
    url(r'^audit/$',views.audit, name='audit'),
    url(r'^session/(\d+)/$',views.session_reccord, name='session_record'),

    url(r'^logout/',views.logout,name='logout'),

    url(r'^login/$',views.login,name='login'),
    url(r'^accounts/profile/$',views.personal),
    url(r'^task/',include("bernard.urls")),


]

bernard/urls.py
from django.conf.urls import include, url

from bernard import views
urlpatterns = [

    url(r'test/$',views.task_test),
    url(r'schedule_index/$',views.schedule_index,name="schedule_index"),
    url(r'plan/(\d+)/$',views.plan_detail,name="plan_detail"),
    url(r'task_order/(\d+)/$',views.save_task_order,name="save_task_order"),

]

kingadmin/urls.py
from django.conf.urls import url,include
from kingadmin import views

urlpatterns = [

    url(r'^login/$', views.acc_login, name="acc_login"),
    url(r'^logout/$', views.acc_logout, name="acc_logout"),
    url(r'^(\w+)/(\w+)/change/(\d+)/password/$', views.password_reset_form, name='password_reset'),
    url(r'^account/password_reset/$', views.personal_password_reset, name='personal_password_reset'),

    url(r'^$', views.app_index, name="table_index"),  # 显示所有注册的表
    url(r'^(\w+)/$', views.app_tables, name="app_tables"),  # 显示每个app里所有注册的表
    url(r'^(\w+)/(\w+)/$',views.display_table_list,name="table_list"), #显示每个表的数据
    url(r'^(\w+)/(\w+)/add/$', views.table_add, name="table_add"),
    url(r'^(\w+)/(\w+)/change/(\d+)/$', views.table_change, name="table_change"),
    #
    url(r'^(\w+)/(\w+)/delete/(\d+)/$', views.table_del, name="table_del"),


]

kingadmin_old/urls.py
from django.conf.urls import url,include
from kingadmin_old import views

urlpatterns = [

    url(r'^login/$', views.acc_login, name="acc_login"),
    url(r'^logout/$', views.acc_logout, name="acc_logout"),
    url(r'^(\w+)/(\w+)/change/(\d+)/password/$', views.password_reset_form, name='password_reset'),
    url(r'^account/password_reset/$', views.personal_password_reset, name='personal_password_reset'),

    url(r'^$', views.app_index, name="table_index"),  # 显示所有注册的表
    url(r'^(\w+)/$', views.app_tables, name="app_tables"),  # 显示每个app里所有注册的表
    url(r'^(\w+)/(\w+)/$',views.display_table_list,name="table_list"), #显示每个表的数据
    url(r'^(\w+)/(\w+)/add/$', views.table_add, name="table_add"),
    url(r'^(\w+)/(\w+)/change/(\d+)/$', views.table_change, name="table_change"),
    #
    url(r'^(\w+)/(\w+)/delete/(\d+)/$', views.table_del, name="table_del"),


]

bernard/models.py
from django.db import models
from web.models import BindHosts,HostGroups
from  django_celery_beat.models import PeriodicTask
# Create your models here.





class Plan(models.Model):
    '''store all task plans'''
    name = models.CharField(max_length=64)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name




class Stage(models.Model):
    'sub steps of one task plan'
    plan = models.ForeignKey(Plan)
    name = models.CharField(max_length=64,default="Default plan")
    order = models.SmallIntegerField(default=1)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "plan:%s stage:%s"%(self.plan,self.name)

class Job(models.Model):
    "one stage can hold a list of jobs"
    stage = models.ForeignKey(Stage)
    name = models.CharField(max_length=64)
    order = models.SmallIntegerField(default=1)
    task_type_choices = (('sshtask','Run Shell Script'),
                         ('scptask','SSH File Transfer')
                         )
    task_type = models.CharField(choices=task_type_choices,max_length=64)
    enabled = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "order:%s, stage:%s,  job:%s"%(self.order,self.stage, self.name)


class SSHTask(models.Model):
    """shell script"""
    job = models.OneToOneField("Job")
    bind_hosts = models.ManyToManyField(BindHosts,blank=True)
    host_groups = models.ManyToManyField(HostGroups,blank=True)
    commands = models.TextField(verbose_name="ssh commands")

    def __str__(self):
        return self.commands


class SCPTask(models.Model):
    """file transfer by scp command"""
    job = models.OneToOneField("Job")
    bind_hosts = models.ManyToManyField(BindHosts, blank=True)
    host_groups = models.ManyToManyField(HostGroups, blank=True)
    local_path = models.CharField(max_length=128)
    remote_path = models.CharField(max_length=128)

    def __str__(self):
        return "%s %s"%(self.local_path,self.remote_path)


class ScheduleLog(models.Model):
    """Store Schedule run logs """
    plan = models.ForeignKey("Plan")
    status_choices = ((0,'failed'),(1,'success'),(2,'error'),(3,'running'))
    status = models.SmallIntegerField(choices=status_choices)
    errors = models.TextField(blank=True,null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(auto_now=True)

bernard/views.py
from django.shortcuts import render,HttpResponse
from bernard import models
import json
# Create your views here.

from  bernard import tasks

def task_test(request):

    res = tasks.add.delay(228,24)
    print("start running task")
    print("async task res",res.get() )

    return HttpResponse('res %s'%res.get())


def schedule_index(request):

    plans = models.Plan.objects.all()
    return render(request,"bernard/schedule_index.html",{'plans':plans})



def plan_detail(request,plan_id):
    plan_obj = models.Plan.objects.get(id=plan_id)
    return render(request,"bernard/plan_detail.html", locals())



def save_task_order(request,plan_id):
    print(request.POST)

    task_orders = json.loads(request.POST.get('tasks'))
    #format: [['1', ['3', '1']], ['2', ['2', '4', '5']]]

    print(task_orders)
    for index,i in enumerate(task_orders):
        print(index,i)
        stage_obj = models.Stage.objects.get(id=i[0])
        stage_obj.order = index
        stage_obj.save()
        job_ids = i[1]
        for job_index,job_id in enumerate(job_ids):
            job_obj = models.Job.objects.get(id=job_id)
            job_obj.order = job_index
            job_obj.save()

    return HttpResponse(json.dumps({'state':'success'}))

templates/bernard/plan_detail.html
{% extends "index.html" %}
{% load bernard_tags %}

{% block page-content %}


<div class="panel panel-primary">

    <!--Panel heading-->
    <div class="panel-heading">
        <div class="panel-control">

            <!--Nav tabs-->
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">Plan</a>
                </li>
                <li class=""><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">任务日志</a>
                </li>
            </ul>

        </div>
        <h3 class="panel-title">{{ plan_obj }}</h3>
    </div>

    <!--Panel body-->
    <div class="panel-body">

        <!--Tabs content-->
        <div class="tab-content">
            <div id="demo-tabs-box-1" class="tab-pane fade active in">
{#                <h4 class="text-thin">First Tab Content</h4>#}
{#                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>#}




                <ul class="stage-sortable">
                    {% get_plan_stages_in_order plan_obj  as plan_stages %}
                    {% for stage in plan_stages %}
                        <li class="ui-state-info stage-ele" stage-id="{{ stage.id }}" style="margin-bottom: 15px">
                           <span style="font-weight: bold;"> {{ stage }}
                            <a class="btn-link pull-right" href="/kingadmin/bernard/stage/change/{{ stage.id }}/" target="_blank">修改</a>
                           </span>
                        <div class="jobs-panel"  style="border: 1px dashed silver;margin-bottom: 10px;margin-top: 5px;padding: 10px">
                            <ul class="job-sortable">
                                {% get_stages_jobs_in_order stage  as stages_jobs %}
                                {% for job in stages_jobs %}
                                <li class="ui-state-default job-ele" job-id="{{ job.id }}" style="margin-top: 5px;padding: 10px">{{ job }}
                                    <a href="/kingadmin/bernard/job/change/{{ job.id }}/" target="_blank" style="color: red" class=" pull-right">修改</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        </li>



                    {% endfor %}
                </ul>

                <div>
                    <button class="btn-info" onclick="SaveTaskOrder()">Save</button>
                </div>
            </div>
            <div id="demo-tabs-box-2" class="tab-pane fade">
                <h4 class="text-thin">Second Tab Content</h4>
                <p>Duis autem vel eum iriure dolor in hendrerit in vulputate.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block bottom-js %}

    <script>
        $(document).ready(function () {
            $( ".stage-sortable" ).sortable();
            $( ".stage-sortable" ).disableSelection();

            $( ".job-sortable" ).sortable();
            $( ".job-sortable" ).disableSelection();

        })



        function SaveTaskOrder(){
            var stages = [];
            $(".stage-ele").each(function () {
                var stage_id = $(this).attr("stage-id");
                var jobs = [];
                var job_eles = $(this).find("li");
                console.log("job items" + job_eles.length)
                $(job_eles).each(function () {

                    jobs.push($(this).attr("job-id"));
                });

                stages.push([stage_id, jobs]);



            })
            console.log(stages);

            $.post("{% url 'save_task_order'  plan_obj.id %}",{tasks:JSON.stringify(stages)},function(callback){
                console.log(callback)
                var callback = JSON.parse(callback);
                if (callback.state == 'success'){
                    $.niftyNoty({
                        type: "success",
                        container : "floating",
                        title : "任务执行顺序已保存",
                        message : "",
                        closeBtn : false,
                        timer : 5000
                    });
                }
            });
        }
    </script>
{% endblock %}

templates/bernard/schedule_index.html
{% extends "index.html" %}
{% load bernard_tags %}

{% block page-content %}
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">定时任务列表</h3>
    </div>
    <div class="panel-body">
        <p>Lorem ipsum dolor sit amet.</p>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Plan ID</th>
                        <th>任务</th>
                        <th>Crontab</th>
                        <th>上次运行时间</th>
                        <th>上次运行结束时间</th>
                        <th>上次运行结果</th>
                        <th>已启用</th>
                    </tr>
                </thead>
                <tbody>

                    {% for plan in plans %}
                    <tr>
                        {% get_plan_last_runlog plan as last_run_log %}
                        {% get_plan_crontab plan as plan_cron_obj%}
                        <td><a href="{% url 'plan_detail' plan.id %}" class="btn-link">{{ plan.id }}</a></td>
                        <td>{{ plan.name }}</td>
                        <td>
                            <a class="btn-link" href="/kingadmin/django_celery_beat/periodictask/change/{{ plan_cron_obj.id }}/" target="_blank">{{ plan_cron_obj }}</a></td>
                        <td>{{ last_run_log.start_date }}</td>
                        <td>{{ last_run_log.end_date }}</td>
                        <td>{{ last_run_log.get_status_display }}</td>
                        <td>{{ plan_cron_obj.enabled }}</td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>

    </div>
</div>
{% endblock %}