CrazyEye/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from web import views,api_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^kingadmin/', include('kingadmin.urls')),
     #url(r'^myadmin/', include(cus_admin.admin_site.urls)),
    url(r'session_security/', include('session_security.urls')),
    url(r'^$',views.dashboard ,name='dashboard'),
    url(r'^hosts/$',views.hosts, name='host_list' ),
    url(r'^hosts/multi/$',views.hosts_multi,name="batch_cmd_exec"),
    url(r'^hosts/crontab/$',views.crontab),
    url(r'^multi_task/log/deatail/(\d+)/$',views.multi_task_log_detail,name='multi_task_log_detail'),
    url(r'^hosts/multi/filetrans$',views.hosts_multi_filetrans,name="batch_file_transfer"),
    url(r'^host/detail/', views.host_detail),
    url(r'^api/',include(api_urls)),
    url(r'^personal/',views.personal,name='personal'),
    url(r'^user_audit/(\d+)/$',views.user_audit, name='user_audit'),
    url(r'^audit/$',views.audit, name='audit'),
    url(r'^session/(\d+)/$',views.session_reccord, name='session_record'),

    url(r'^logout/',views.logout,name='logout'),

    url(r'^login/$',views.login,name='login'),
    url(r'^accounts/profile/$',views.personal),
    url(r'^task/',include("bernard.urls")),


]

bernard/urls.py
from django.conf.urls import include, url

from bernard import views
urlpatterns = [

    url(r'test/$',views.task_test),
    url(r'schedule_index/$',views.schedule_index,name="schedule_index"),
    url(r'plan/(\d+)/$',views.plan_detail,name="plan_detail"),
    url(r'task_order/(\d+)/$',views.save_task_order,name="save_task_order"),

]

kingadmin/urls.py
from django.conf.urls import url,include
from kingadmin import views

urlpatterns = [

    url(r'^login/$', views.acc_login, name="acc_login"),
    url(r'^logout/$', views.acc_logout, name="acc_logout"),
    url(r'^(\w+)/(\w+)/change/(\d+)/password/$', views.password_reset_form, name='password_reset'),
    url(r'^account/password_reset/$', views.personal_password_reset, name='personal_password_reset'),

    url(r'^$', views.app_index, name="table_index"),  # 显示所有注册的表
    url(r'^(\w+)/$', views.app_tables, name="app_tables"),  # 显示每个app里所有注册的表
    url(r'^(\w+)/(\w+)/$',views.display_table_list,name="table_list"), #显示每个表的数据
    url(r'^(\w+)/(\w+)/add/$', views.table_add, name="table_add"),
    url(r'^(\w+)/(\w+)/change/(\d+)/$', views.table_change, name="table_change"),
    #
    url(r'^(\w+)/(\w+)/delete/(\d+)/$', views.table_del, name="table_del"),


]

kingadmin_old/urls.py
from django.conf.urls import url,include
from kingadmin_old import views

urlpatterns = [

    url(r'^login/$', views.acc_login, name="acc_login"),
    url(r'^logout/$', views.acc_logout, name="acc_logout"),
    url(r'^(\w+)/(\w+)/change/(\d+)/password/$', views.password_reset_form, name='password_reset'),
    url(r'^account/password_reset/$', views.personal_password_reset, name='personal_password_reset'),

    url(r'^$', views.app_index, name="table_index"),  # 显示所有注册的表
    url(r'^(\w+)/$', views.app_tables, name="app_tables"),  # 显示每个app里所有注册的表
    url(r'^(\w+)/(\w+)/$',views.display_table_list,name="table_list"), #显示每个表的数据
    url(r'^(\w+)/(\w+)/add/$', views.table_add, name="table_add"),
    url(r'^(\w+)/(\w+)/change/(\d+)/$', views.table_change, name="table_change"),
    #
    url(r'^(\w+)/(\w+)/delete/(\d+)/$', views.table_del, name="table_del"),


]

web/models.py
#_*_coding:utf-8_*_
from django.db import models
import django
from django.contrib.auth.models import User
import datetime
from web import auth
# Create your models here.




class IDC(models.Model):
    name = models.CharField(max_length=64,unique=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'IDC'
        verbose_name_plural = 'IDC'

class Department(models.Model):
    name = models.CharField(max_length=64,unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '部门'
        verbose_name_plural = '部门'

class Hosts(models.Model):
    hostname = models.CharField(max_length=64,unique=True)
    ip_addr = models.GenericIPAddressField(unique=True)
    system_type_choices = (
        ('windows','Windows'),
        ('linux', 'Linux/Unix')
    )
    idc = models.ForeignKey('IDC')
    system_type = models.CharField(choices=system_type_choices,max_length=32,default='linux')
    port = models.IntegerField(default=22)
    enabled = models.BooleanField(default=True,help_text='主机若不想被用户访问可以去掉此选项')
    #host_users = models.ForeignKey('HostUsers')
    #host_groups = models.ForeignKey('HostGroups')
    memo = models.CharField(max_length=128,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s(%s)' %(self.hostname,self.ip_addr)

    class Meta:
        verbose_name = '主机'
        verbose_name_plural = '主机'

class HostUsers(models.Model):
    auth_method_choices = (('ssh-password',"SSH/ Password"),('ssh-key',"SSH/KEY"))
    auth_method = models.CharField(choices=auth_method_choices,max_length=16,help_text='如果选择SSH/KEY，请确保你的私钥文件已在settings.py中指定')
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64,blank=True,null=True,help_text='如果auth_method选择的是SSH/KEY,那此处不需要填写..')
    memo = models.CharField(max_length=128,blank=True,null=True)

    def __str__(self):
        return '%s(%s)' %(self.username,self.password)

    class Meta:
        verbose_name = '远程用户'
        verbose_name_plural = '远程用户'
        unique_together = ('auth_method','password','username')

class BindHosts(models.Model):
    host = models.ForeignKey('Hosts')
    host_user = models.ForeignKey('HostUsers',verbose_name="远程用户")

    enabled = models.BooleanField(default=True)

    def __str__(self):
        return '%s:%s' %(self.host.hostname,self.host_user.username)

    class Meta:
        unique_together = ("host", "host_user")
        verbose_name = '主机与远程用户绑定'
        verbose_name_plural = '主机远程与用户绑定'

    # def get_groups(self):
    #         return ",\n".join([g.name for g in self.host_group.all()])

class HostGroups(models.Model):
    name = models.CharField(max_length=64,unique=True)
    memo = models.CharField(max_length=128,blank=True,null=True)
    bind_hosts = models.ManyToManyField('BindHosts',blank=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '主机组'
        verbose_name_plural = '主机组'


#class UserProfile(AbstractBaseUser):
class UserProfile(auth.AbstractBaseUser,auth.PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        verbose_name='staff status',
        default=False,
        help_text='Designates whether the user can log into this admin site.',
    )
    name = models.CharField(max_length=32)
    #token = models.CharField('token', max_length=128,default=None,blank=True,null=True)
    department = models.ForeignKey('Department',verbose_name='部门',blank=True,null=True)
    host_groups = models.ManyToManyField('HostGroups',verbose_name='授权主机组',blank=True)
    bind_hosts = models.ManyToManyField('BindHosts',verbose_name='授权主机',blank=True)


    memo = models.TextField('备注', blank=True,null=True,default=None)
    date_joined = models.DateTimeField(blank=True,null=True, auto_now_add=True)
    valid_begin_time = models.DateTimeField(default=django.utils.timezone.now,help_text="yyyy-mm-dd HH:MM:SS")
    valid_end_time = models.DateTimeField(blank=True,null=True,help_text="yyyy-mm-dd HH:MM:SS")


    USERNAME_FIELD = 'email'
    #REQUIRED_FIELDS = ['name','token','department','tel','mobile','memo']
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __str__ on Python 2
        return self.email

    # def has_perm(self, perm, obj=None):
    #     "Does the user have a specific permission?"
    #     # Simplest possible answer: Yes, always
    #     return True
    def has_perms(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    # @property
    # def is_staff(self):
    #     "Is the user a member of staff?"
    #     # Simplest possible answer: All admins are staff
    #     return self.is_admin
    @property
    def is_superuser(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = u"用户信息"

    def __str__(self):
        return self.name

    objects = auth.UserManager()

    
    class Meta:
        verbose_name = 'CrazyEye账户'
        verbose_name_plural = 'CrazyEye账户'

        permissions = (
            ('web_access_dashboard', '可以访问 审计主页'),
            ('web_batch_cmd_exec', '可以访问 批量命令执行页面'),
            ('web_batch_batch_file_transfer', '可以访问 批量文件分发页面'),
            ('web_config_center', '可以访问 堡垒机配置中心'),
            ('web_config_items', '可以访问 堡垒机各配置列表'),
            ('web_invoke_admin_action', '可以进行admin action执行动作'),
            ('web_table_change_page', '可以访问 堡垒机各配置项修改页'),
            ('web_table_change', '可以修改 堡垒机各配置项'),
        )

#
# class UserProfile(models.Model):
#     user = models.OneToOneField(User)
#     name = models.CharField(unique=True,max_length=32)
#     department = models.ForeignKey('Department',verbose_name='部门')
#     #user_groups = models.ManyToManyField('PUserGroups') #might use it in the future version
#     host_groups = models.ManyToManyField('HostGroups',verbose_name='授权主机组',blank=True)
#     bind_hosts = models.ManyToManyField('BindHosts',verbose_name='授权主机',blank=True)
#     valid_begin_time = models.DateTimeField(default=django.utils.timezone.now)
#     valid_end_time = models.DateTimeField()
#
#     def __str__(self):
#         return self.name
#     class Meta:
#         verbose_name = 'CrazyEye账户'
#         verbose_name_plural = 'CrazyEye账户'

class SessionTrack(models.Model): #没用了的表

    date = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField(default=False)
    def __str__(self):
        return '%s' %self.id


class Session(models.Model):
    '''生成用户操作session id '''
    user = models.ForeignKey('UserProfile')
    bind_host = models.ForeignKey('BindHosts')
    tag = models.CharField(max_length=128,default='n/a')
    closed = models.BooleanField(default=False)
    cmd_count = models.IntegerField(default=0) #命令执行数量
    stay_time = models.IntegerField(default=0, help_text="每次刷新自动计算停留时间",verbose_name="停留时长(seconds)")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<id:%s user:%s bind_host:%s>' % (self.id,self.user.email,self.bind_host.host)
    class Meta:
        verbose_name = '审计日志'
        verbose_name_plural = '审计日志'


#Deprecated
class AuditLog(models.Model):
    session = models.ForeignKey(SessionTrack)
    user = models.ForeignKey('UserProfile')
    host = models.ForeignKey('BindHosts')
    action_choices = (
        (0,'CMD'),
        (1,'Login'),
        (2,'Logout'),
        (3,'GetFile'),
        (4,'SendFile'),
        (5,'exception'),
    )
    action_type = models.IntegerField(choices=action_choices,default=0)
    cmd = models.TextField(blank=True,null=True)
    memo = models.CharField(max_length=128,blank=True,null=True)
    date = models.DateTimeField()


    def __str__(self):
        return '%s-->%s@%s:%s' %(self.user.email,self.host.host_user.username,self.host.host.ip_addr,self.cmd)
    class Meta:
        verbose_name = '审计日志old'
        verbose_name_plural = '审计日志old'



class TaskLog(models.Model):
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True,blank=True)
    task_type_choices = (('cmd',"CMD"),('file_send',"批量发送文件"),('file_get',"批量下载文件"))
    task_type = models.CharField(choices=task_type_choices,max_length=50)
    files_dir = models.CharField("文件上传临时目录",blank=True,null=True,max_length=32)
    user = models.ForeignKey('UserProfile')
    hosts = models.ManyToManyField('BindHosts')
    cmd = models.TextField()
    expire_time = models.IntegerField(default=30)
    task_pid = models.IntegerField(default=0)
    note = models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return "taskid:%s cmd:%s" %(self.id,self.cmd)

    class Meta:
        verbose_name = '批量任务'
        verbose_name_plural = '批量任务'

class TaskLogDetail(models.Model):
    child_of_task = models.ForeignKey('TaskLog')
    bind_host  = models.ForeignKey('BindHosts')
    date = models.DateTimeField(auto_now_add=True) #finished date
    event_log = models.TextField()
    result_choices= (('success','Success'),('failed','Failed'),('unknown','Unknown'))
    result = models.CharField(choices=result_choices,max_length=30,default='unknown')

templates/host_detail.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
主机详情
{% endblock %}
{% block page-content %}

<div class="row">
     <div class="col-sm-6 col-lg-3">
        <div class="panel" style="height: 492px;">
            <div class="panel-heading">
                <h3 class="panel-title">主机列表</h3>
            </div>
            <div  class="panel-body " style="overflow: auto" >

                      <input style="margin-bottom: 5px" type="text" oninput="SearchHost(this)" id="host_search" class="form-control" placeholder="查找主机...">

                <div id="host_list" style="">
                    <div style="margin-bottom:0;" class="list-group bg-trans">
                     {% for host in all_hosts %}

                            {% if host.id == current_host_id %}
                                <a class="list-group-item active" host_id="{{ host.id }}" href="/host/detail/?host_id={{host.id }}">{{ host.hostname }}({{ host.ip_addr }})</a>
                            {% else %}
                                <a class="list-group-item" host_id="{{ host.id }}" href="/host/detail/?host_id={{host.id }}" >{{ host.hostname }}({{ host.ip_addr }})</a>
                            {% endif %}
                     {% endfor %}
                     </div>
                </div>




            </div>
        </div>
     </div>

    <div class="col-sm-6 col-lg-9">
        <div class="panel">
             <div class="panel-heading">
                <h3 class="panel-title">主机信息</h3>
            </div>
            <div class="panel-body" >

                {% for host in all_hosts %}

                    {% if host.id == current_host_id %}
                    <div class="row" >
                        <label class="col-md-2 control-label">主机名(IP)</label>
                        <div  class="col-md-9 ">
                            <b>{{ host }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">操作系统</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.system_type }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">端口</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.port }}</b>
                        </div>
                    </div>

                    <div class="row" >
                        <label class="col-md-2 control-label">所在机房</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.idc }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">主机状态</label>
                        <div  class="col-md-9 ">
                            {% if host.enabled %}
                            <span class="badge badge-success">已启用</span>
                            {% else %}
                            <span class="badge badge-danger">已停用</span>
                            {% endif %}
                        </div>
                    </div>


                    <div class="row" >
                        <label class="col-md-2 control-label">已绑定远程用户信息</label>
                        <div  class="col-md-9 ">
                            {% for bind_host in host.bindhosts_set.select_related %}
                            <div><b>{{ bind_host.host_user.username }}
                                -->属组:{% for group in  bind_host.hostgroups_set.select_related %}
                                    <span class="badge badge-info">{{ group.name }}</span>{% endfor %}</b>
                                {% if not bind_host.enabled %}<span class="badge badge-danger">此账户已禁用</span>{% endif %}
                            </div>

                            {% endfor %}
                        </div>
                    </div>


                    <div class="row" >
                        <hr/>
                        <label class="col-md-2 control-label panel-title">用户访问纪录</label>

                        <table class="table table-hover">
                            <tr>
                                <th>会话ID</th>
                                <th>操作用户</th>
                                <th>远程用户</th>
                                <th>登录日期</th>
                                <th>停留时长</th>
                                <th>命令数</th>
                                <th>状态</th>

                            </tr>
                            {% for log in access_records %}
                            <tr>
                                <td>{{ log.id }}</td>
                                <td data-label="hostname" class="hide" >{{ log.host.host.hostname }}</td>
                                <td>{{ log.user.name }}</td>
                                <td data-label="username">{{ log.bind_host.host_user.username }}</td>
                                <td data-label="login-date">{{ log.date |date:"Y-m-d H:i:s" }}</td>
                                <td data-label="stay-time">{% get_time_humanize_display log.stay_time %}</td>
{#                                <td data-label="logout-date">{% query_logout_date  log.session.auditlog_set.select_related 'action_type' 2 %}</td>#}
                                <td ><a href="#" onclick="ShowRecordDetail(this,'{{ log.session.id }}')" class="btn-link">{{ log.cmd_count }}</a></td>
                                {% if log.closed %}
                                    <td ><span class="badge badge-info">已结束</span></td>
                                {% else %}
                                    <td><span class="badge badge-success">连接中</span></td>
                                {% endif %}
                            </tr>
                            {% endfor %}

                        </table>
                        <div class="pagination pull-right ">
                            {% pagenator2 access_records 'host_id' current_host_id %}
                        </div>
                    </div>




                    {% endif %}

                {% endfor %}

            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block bottom-js %}
<script type="text/javascript">

    $(document).ready(function(){

        host_list = {};
        $("#host_list div").children().each(function(index){

          host_list[$(this).attr("host_id")] = $(this).text();
        });

        $("#host_list a[host_id='" + "{{ current_host_id }}" + "']").prependTo("#host_list div");
        console.log($("#host_list active")[0])


    });//end doc ready

    function SearchHost(ele){

        var search_str = $(ele).val()
        var host_list_html ='' ;

        $.each(host_list,function(host_id,val){
            if (val.indexOf(search_str) >-1){
                console.log(val);
                var html_row = "<a class='list-group-item' host_id='" + host_id + "' href='/host/detail/?host_id=" + host_id + "' > " + val + "</a>";
                host_list_html += html_row ;

            }

        });//end each

        $("#host_list").html(host_list_html);
    }


</script>
{% endblock %}

templates/user_audit.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
用户审计
{% endblock %}
{% block page-content %}
<div class="row" >
    <div class="col-sm-6 col-lg-3">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">用户列表</h3>
            </div>
            <div class="panel-body" >
                <div class="list-group bord-no">

                {% for department in department_list %}
                    <a data-label="department-name" class=" list-group-item" href="#"><b>{{ department }}</b><span style="color:red" class="badge badge-info">{{ department.userprofile_set.select_related|length }}</span></a>
                    {% for user in department.userprofile_set.select_related %}

                        <a data-label="username"  user-id="{{ user.id }}" style="margin-left:2%;width:96%" class="list-group-item  collapse" href="/user_audit/{{ user.id }}/">&nbsp;&nbsp;&nbsp;{{ user.name }}</a>
                    {% endfor %}
                {% endfor %}
                </div>
            </div>
        </div>

    </div> <!--end col-lg-3-->
    <div class="col-sm-6 col-lg-9">
        <div class="panel">

            <div class="panel-body" style="margin-left:0" >

                <div class="row" >
                    <label class="col-md-2 control-label">账户</label>
                    <div  class="col-md-9 ">
                        <b>{{ user_obj.name}}</b>

                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">部门</label>
                    <div  class="col-md-9 ">
                        <b>{{ user_obj.department.name}}</b>

                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">账户有效期</label>
                    <div  class="col-md-9 ">
                        从 <b>{{ user_obj.valid_begin_time }}</b> 至 <b>{{ user_obj.valid_end_time }}</b>
                        <hr/>
                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">可管理主机组</label>
                    <div  class="col-md-9 ">
                        {% for group in user_obj.host_groups.select_related %}
                        {{ group.name }}<br>
                        {% endfor %}
                    <hr/>
                    </div>
                </div>

                <div class="row" >
                    <label class="col-md-2 control-label">可操作主机列表</label>
                    <div  class="col-md-9 ">

                        <table class="table  table-hover table-condensed">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>主机名</th>
                                <th>IP</th>
                                <th>远程用户</th>
                            </tr>
                        </thead>
                        <tbody>
                         {% for bind_host in user_obj.bind_hosts.select_related %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="#fakelink" class="btn-link">{{ bind_host.host.hostname}}</a></td>
                                <td>{{  bind_host.host.hostname }} </td>
                                <td>{{  bind_host.host_user.username }} </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                        </table>


                     <hr/>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-lg-12">

        <div class="panel panel-primary">

            <!--Panel heading-->
            <div class="panel-heading">
                <div class="panel-control">

                    <!--Nav tabs-->
                    <ul class="nav nav-tabs">
                        {% if data_type == 'multi_task' %}

                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% else %}
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% endif %}
                    </ul>

                </div>
                <h3 class="panel-title"><b>{{ user_obj.name }}</b> 的操作纪录</h3>
            </div>

            <!--Panel body-->
            <div class="panel-body">

                <!--Tabs content-->
                <div class="tab-content">
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-1" class="tab-pane fade">
                    {% else %}
                    <div id="demo-tabs-box-1" class="tab-pane fade active in ">
                    {% endif %}
                      <table class="table  table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>#</th>

                                    <th>主机名</th>
                                    <th>IP</th>
                                    <th>远程用户</th>
                                    <th>登录日期</th>
                                    <th>登出日期</th>
                                    <th>操作指令数</th>
                                    <th>#</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for record in user_login_records %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td data-label="hostname"><a href="#fakelink" class="btn-link">{{ record.host.host.hostname}}</a></td>
                                    <td data-label="ip_addr">{{ record.host.host.ip_addr }} </td>
                                    <td data-label="username">{{ record.host.host_user.username }} </td>
                                    <td data-label="login_date"><b >{{ record.date|date:"Y-m-d H:i" }}</b> </td>
                                    <td data-label="logout_date">{{ record.session.auditlog_set.select_related.last.date|date:"Y-m-d H:i" }} </td>
                                    <td>{{ record.session.auditlog_set.select_related.count}} </td>
                                    <td><a onclick="ShowRecordDetail(this,'{{ record.session.id }}')"  class="badge badge-success">查看详细</a> </td>
                                </tr>
                                {% endfor %}
                           </tbody>

                      </table>

                    <div class="pagination pull-right ">
                        {% pagenator user_login_records 'cmd_log' %}
                    </div>

                    </div>
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-2" class="tab-pane fade active in">
                    {% else %}
                    <div id="demo-tabs-box-2" class="tab-pane fade">
                    {% endif %}

                          <table class="table  table-hover table-condensed">
                                <thead>
                                    <tr>
                                        <th>#</th>

                                        <th>任务ID</th>
                                        <th>任务类型</th>
                                        <th>任务内容</th>
                                        <th>成功数</th>
                                        <th>失败数</th>
                                        <th>未知数</th>
                                        <th>详细</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    {% for record in multitask_records %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ record.id }}</td>
                                        <td>{{ record.task_type }}</td>
                                        <td>{{ record.cmd }}</td>
                                         <td>{% query_set record.tasklogdetail_set "result" "success" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "failed" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "unknown" %}</td>
                                        <td><a class="badge badge-info" href="{% url 'multi_task_log_detail' record.id %}">查看详细</a></td>

                                    </tr>
                                    {% endfor %}
                               </tbody>

                          </table>

                        <div class="pagination pull-right ">
                            {% pagenator multitask_records 'multi_task' %}
                        </div>


                    </div>
                </div>
            </div>
        </div>



    </div> <!--end col-sm-6 col-lg-12-->
</div>

{% include 'user_audit_modal.html' %}


{% endblock %}
{% block aside-bar %}

{% endblock %}
{% block bottom-js %}
{% include 'user_audit_js.html' %}
<script type="text/javascript" >


    $(document).ready(function(){

        if ("{{ data_type }}" == 'multi_task'){

        }

        $("a[data-label='department-name']").click(function(){
            $(this).toggleClass('active');

            $(this).nextUntil("a[data-label='department-name']").toggleClass("collapse");
        });//end click
        $("a[data-label='username']").click(function(){

            $(this).parent().children("a[data-label='username']").removeClass("btn-default");
            $(this).addClass("btn-default");

        });//end click


        //highlight the active user when page loaded
        var active_user_ele = $("a[user-id='{{ user_obj.id }}']");
        active_user_ele.toggleClass("collapse");
        if (active_user_ele.prev().attr('data-label') == 'department-name'){
            active_user_ele.prev().toggleClass('active');
        }else{
            var parent_node = active_user_ele.prevUntil("a[data-label='department-name']")[0];
            $(parent_node).prev().toggleClass('active');

        }
        //end highlight the active user when page loaded

    });


</script>
{% endblock %}